spring.security.oauth2.client.registration.auth0.client-secret=b34rS8MZdqLFR41OgIpn1ffitzNYEhAKdqKQ2LxCmtf0evCoHU3bDsyylku_e2Jr
spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888